spring.application.name=volunteer-form-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/volunteer_form}
spring.datasource.username=${DB_USERNAME:volunteer_form}
spring.datasource.password=${DB_PASSWORD:volunteer_form}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
